### PR TITLE
Make SlashCommand#getHelp() return translated text when available.

### LINKED ISSUE #89: Translations from property file not applied?
### Issue Checklist

- [X] I have checked for similar issues on the [Issue tracker](https://github.com/Chew/JDA-Chewtils/issues)
- [X] I have updated to the [latest version](https://github.com/Chew/JDA-Chewtils/releases) of JDA-Chewtils.
- [X] I have checked the branches or the maintainer's PRs for upcoming bug fixes.

### Affected Modules

Command

### Description

I'm unsure what exactly the issue here is, if it is an issue at all, but it seems like that translations from a properties file using the TranslateUtil are not applied?

To give some context, I have this properties file named `commands_en-GB.properties`:
```properties
COMMAND_BLUSH_NAME=blush
COMMAND_BLUSH_DESCRIPTION=Shows that you are blushing.
```

Then in my main Bot class am I doing this:
```java
private void resolveCommandTranslations(){
    TranslateUtil.setDefaultLocale(DiscordLocale.ENGLISH_UK);
    int translations = 0;
    for(TranslationManager.Lang lang : fileManager.getLanguages()){
        if(!lang.supportedLocale())
            continue;
        
        try{
            Properties properties = new Properties();
            properties.load(getClass().getResourceAsStream("/lang/commands_" + lang.key() + ".properties"));
            TranslateUtil.addLocale(lang.discordLocale(), properties);
            
            translations++;
        }catch(IOException ex){
            logger.warn("Encountered IOException while trying to load commands_{}.properties.", lang.key(), ex);
        }
    }
    
    logger.info("Resolved {} Command translations.", translations);
}
```
Finally, I override the SlashCommand class to implement some own stuff, including a central command handling.
One thing I do there too is set the `nameLocalization` and `descriptionLocalization` values like this:
```java
/*
 * Used for commands who don't have a different name in the properties file.
 */
public BotCommand(String name){
    this(name, name);
}

/*
 * Name is used for the propertyPrefix, allowing to separate duplicate names (i.e. from sub-commands)
 * While label would be the name used for the (sub-)command.
 */
public BotCommand(String name, String label){
    String propertyPrefix = "COMMAND_" + name.toUpperCase(Locale.ROOT);
    
    this.name = label
    
    this.nameLocalization = TranslateUtil.buildLocaleMap(propertyPrefix + "_NAME");
    this.descriptionLocalization = TranslateUtil.buildLocaleMap(propertyPrefix + "_DESCRIPTION");
}
```

When I now run the bot does it report to have resolved 1 translation, but when typing the command - in my case /blush - does it show this:
grafik

This makes me believe that the localizations aren't applied and only the name and value are set...

### PR DESCRIPTION
**Pull request by Andre601**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing
[pull-request]: https://github.com/JDA-Applications/JDA-Utilities/pulls

#### Pull Request Checklist
Please follow the following steps before opening this PR.<br>
PRs that do not complete the checklist will be subject to denial for
missing information.

- [x] I have checked the [pull request page][pull-request] for upcoming
      or merged features/bug fixes.
- [x] I have read JDA's [contributing guidelines][contributing].

#### Pull Request Information
Check and fill in the blanks for all that apply:

- [ ] My PR fixes a bug, error, or other issue with the library's codebase.
- [x] My PR is for the `commands` module of the JDA-Utilities library.
- [ ] My PR creates a new module for the JDA-Utilities library: `______`.

#### Description

This overrides the `getHelp()` method to return a translated description using the default locale through `getDescriptionLocalization().get(TranslateUtil.getDefaultLocale)`
This should allow a user to set the description within the localization files without needing to set the `help` text itself.
Should there be no localized description for the default locale (Be null or empty) will it default to using `this.help`

This also adds `getDefaultLocale()` in the TranslateUtil to retrieve the default locale that was set.

I didn't add the same functionality to the name, as names in SlashCommands need to be alphanummeric when creating, which with this aproach would be problematic.

Given that this overrides a method for SlashCommand, should it automatically also be applied to Subcommands too.

Closes #89

### CODE REVIEW

File: command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java [hunk 1]
```diff
@@ -177,6 +178,24 @@ public void onAutoComplete(CommandAutoCompleteInteractionEvent event) {}
...
+     * @return Translated Help text for default locale, or help text set in constructor.
+     */
+    @Override
+    public String getHelp(){
+        String helpMessage = null;
+        if (!getDescriptionLocalization().isEmpty()) {
+            helpMessage = getDescriptionLocalization().get(TranslateUtil.getDefaultLocale());
+        }
+        
+        return (helpMessage == null || helpMessage.isEmpty()) ? this.help : helpMessage;
```
Comment (Chew) [inline command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java:207]: We should always return this.help if it is specified, and only do this logic if it's not

Comment (Andre601) [reply command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java:207]: Sorry for a late reply... Honestly forgot this.

The main issue is, that help is always there. By default is it `no help available`, so if we should have this logic will this require modifications to the default help message (i.e. make it null and have `getHelp()` return the default text in case of null), which I feel like a breaking change here.

Maybe another aproach could be a dedicated option and getter for the command description for slash commands that defaults to returning `getHelp()` if nothing is set?

Comment (Andre601) [reply command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java:207]: Any input on this?

Comment (Chew) [reply command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java:207]: Oh yeah that's a good point, hmm.

Logically the description localization overwrites the help message in the default language to begin with, not sure what I was saying here.

File: command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java [hunk 2]
```diff
@@ -187,6 +188,24 @@ public void onAutoComplete(CommandAutoCompleteInteractionEvent event) {}
...
+    /**
+     * Returns the description of this SlashCommand instance.<br>
+     * Should there be {@link #getDescriptionLocalization() translations for this text} will the client try to
+     * obtain a translation for the Description using {@link TranslateUtil#getDefaultLocale() the default locale} and
+     * in case of a null or empty String return the default help text set.
+     * 
+     * @return Translated Help text for default locale, or help text set in constructor.
+     */
+    @Override
+    public String getHelp(){
```
Comment (Chew) [inline command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java]:
```suggestion
    public String getHelp() {
```

**Review by Chew — APPROVED** [review]

**Comment by Chew** [comment]
After testing this I think the solution here might be setting this.help to "null" by default then falling back to "no help available" if there's no help in that locale. However, Discord natively uses fallback to whatever language is available, so it's really not a big deal here. Frankly it should be deprecated entirely, but that's not the scope here.
