### PR TITLE
Fix of the default prefix @mention that was no longer responding to commands

### LINKED ISSUE #39: Default @mention prefix no longer respected
### Issue Checklist

- [X] I have checked for similar issues on the [Issue tracker](https://github.com/Chew/JDA-Chewtils/issues)
- [X] I have updated to the [latest version](https://github.com/Chew/JDA-Chewtils/releases) of JDA-Chewtils.
- [X] I have checked the branches or the maintainer's PRs for upcoming bug fixes.

### Affected Modules

Command

### Description

When I try to use the mention prefix, it dont work at all with Chewtils.
I've tryed doing the same on JDA-Utilities and it work

image

### PR DESCRIPTION
**Pull request by brandonfl**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing
[pull-request]: https://github.com/JDA-Applications/JDA-Utilities/pulls

#### Pull Request Checklist
Please follow the following steps before opening this PR.<br>
PRs that do not complete the checklist will be subject to denial for
missing information.

- [x] I have checked the [pull request page][pull-request] for upcoming
      or merged features/bug fixes.
- [x] I have read JDA's [contributing guidelines][contributing].

#### Pull Request Information
Check and fill in the blanks for all that apply:

- [x] My PR fixes a bug, error, or other issue with the library's codebase.
- [ ] My PR is for the `______` module of the JDA-Utilities library.
- [ ] My PR creates a new module for the JDA-Utilities library: `______`.

#### Description

Fix the bug https://github.com/Chew/JDA-Chewtils/issues/39 introduced in pr https://github.com/Chew/JDA-Chewtils/pull/13

The default @mention prefix will always be followed by a space since it's a mention. 
Meaning this space is part of the prefix ! 
So need to add into counter the `>` character and the space, so 2 characters

image

as the `makeMessageParts` use `substring(prefixLength, i)` it detect the whitespace as the command and the real command as the argument...

image

Related code : 

[makeMessageParts into CommandClientImpl.java  lines 739-L752](https://github.com/freya022/JDA-Chewtils/blob/f5d904a3ac3cbd2846970802ff260098f68ed10f/command/src/main/java/com/jagrosh/jdautilities/command/impl/CommandClientImpl.java#L739-L752)

### CODE REVIEW

**Comment by freya022** [comment]
Nevermind, had a wrong master branch selected

This PR *should* fix it

File: command/src/main/java/com/jagrosh/jdautilities/command/impl/CommandClientImpl.java [hunk 1]
```diff
@@ -666,7 +666,7 @@ private MessageParts getParts(MessageReceivedEvent event) {
         if(prefix.equals(DEFAULT_PREFIX) || (altprefix != null && altprefix.equals(DEFAULT_PREFIX))) {
             if(rawContent.startsWith("<@"+ event.getJDA().getSelfUser().getId()+">") ||
                     rawContent.startsWith("<@!"+ event.getJDA().getSelfUser().getId()+">")) {
-                final int prefixLength = rawContent.indexOf('>') + 1;
+                final int prefixLength = rawContent.indexOf('>') + 2;
```
Comment (freya022) [inline command/src/main/java/com/jagrosh/jdautilities/command/impl/CommandClientImpl.java:672]: I suggest you add a comment saying why the + 2 is needed

Comment (brandonfl) [reply command/src/main/java/com/jagrosh/jdautilities/command/impl/CommandClientImpl.java:672]: Ok will add comment asap

Comment (brandonfl) [reply command/src/main/java/com/jagrosh/jdautilities/command/impl/CommandClientImpl.java:672]: Sorry for the wait, I have added comments with the commit b5402a9d1f72b8ec9afd1be519cd089017f8e635. 
I hope that is explicit, English is not my native language

**Review by Chew — APPROVED** [review]
